base_package_groups:
    - "@development-tools"
    - "@C Development Tools and Libraries"
    - "@Container Management"
    - "@Administration Tools"
    - "@Standard"
    - "@System Tools"

install_multimedia_group: false
install_hardware_support_group: false

optional_package_groups:
    multimedia: "@Multimedia"
    hardware_support: "@Hardware Support"

base_packages_core:
    - zsh
    - git
    - curl
    - wget
    - fastfetch
    - ripgrep
    - fd-find
    - fzf
    - bat
    - jq
    - htop
    - btop
    - cmatrix
    - tree
    - unzip
    - zip
    - rsync
    - stow
    - zoxide
    - shellcheck
    - wl-clipboard
    - rbw
    - flatpak
    - fontconfig
    - dnf-plugins-core
    - NetworkManager-openvpn
    - openvpn
    - wireguard-tools
    - nmap
    - dconf
    - avahi
    - nss-mdns
    - snapper
    - restic
    - firewalld
    - cava

base_packages_dev:
    - neovim
    - helix
    - golang
    - golang-x-tools-devel
    - delve
    - rust
    - cargo
    - podman
    - podman-compose

base_packages_gui:
    - libreoffice
    - thunderbird
    - gnome-control-center
    - gnome-software
    - gnome-disk-utility
    - nautilus
    - gimp
    - inkscape
    - krita

repo_packages:
    - code
    - google-chrome-stable

flatpak_apps:
    - io.dbeaver.DBeaverCommunity
    - com.usebruno.Bruno
    - org.localsend.localsend_app
    - com.discordapp.Discord
    - com.slack.Slack

install_youtube_music_rpm: true
youtube_music_rpm_url: "https://github.com/pear-devs/pear-desktop/releases/download/v3.11.0/youtube-music-3.11.0.x86_64.rpm"

go_tools:
    - name: air
      module: github.com/air-verse/air@latest
      binary: air

virtualization_packages:
    - qemu-kvm
    - libvirt
    - libvirt-daemon-kvm
    - libvirt-daemon-config-network
    - virt-install
    - virt-manager
    - virt-viewer
    - edk2-ovmf
    - swtpm
    - guestfs-tools
    - virt-top

greetd_packages:
    - greetd
    - dms-greeter

install_greetd_if_no_dm: true
force_greetd: true

core_services:
    - firewalld
    - fstrim.timer
    - avahi-daemon

nerd_fonts:
    - name: JetBrainsMono
      url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
    - name: CascadiaCode
      url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip

dms_copr_repo: avengemedia/dms-git
dms_copr_repo_file: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:avengemedia:dms-git.repo

ghostty_copr_repo: scottames/ghostty
ghostty_copr_repo_file: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:scottames:ghostty.repo

yazi_copr_repo: lihaohong/yazi
yazi_copr_repo_file: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:lihaohong:yazi.repo

starship_copr_repo: atim/starship
starship_copr_repo_file: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:starship.repo

install_anytype_rpm: true
anytype_rpm_url: ""

install_steam: false
gaming_packages:
    - steam
