[shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
opacity = 0.90
blur = true

[font]
size = 12

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[cursor]
style.shape = "Underline"
vi_mode_style = "Block"

[[keyboard.bindings]]
key = "v"
mods = "Control"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"
