import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
opacity = 0.96
blur = true

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[cursor]
style.shape = "Underline"
vi_mode_style = "Block"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"
