[colors.primary]
background = '#131318'
foreground = '#e4e1e9'

[colors.selection]
text = '#e4e1e9'
background = '#3d4279'

[colors.cursor]
text = '#131318'
cursor = '#bdc2ff'

[colors.normal]
black   = '#131318'
red     = '#ff7295'
green   = '#7fff95'
yellow  = '#ffd872'
blue    = '#a7acf2'
magenta = '#3e4276'
cyan    = '#bdc2ff'
white   = '#eff0ff'

[colors.bright]
black   = '#999aa5'
red     = '#ff9fb7'
green   = '#a5ffb5'
yellow  = '#ffe6a5'
blue    = '#c6cbff'
magenta = '#d0d4ff'
cyan    = '#e1e3ff'
white   = '#f8f9ff'
